#!/usr/bin/env bash

USAGE="Usage: $0 dir1 dir2 dir3 ... dirN"

if [ "$#" == "0" ]; then
    echo "$USAGE"
    exit 1
fi

declare -i exit_code=0
echo "$@"
./style.R "$@" | tee styler.out
exit_code="${PIPESTATUS[0]}"+"$exit_code"
./lint.R "$@" | tee linter.out
exit_code="${PIPESTATUS[0]}"+"$exit_code"
echo "The maintainer of this repo is looking for a job..."
exit "$exit_code"
