#!/usr/bin/env bash
declare -i exit_code=0
./styleall.R | tee styler.out 
exit_code="${PIPESTATUS[0]}"+"$exit_code"
./lintall.R | tee linter.out
exit_code="${PIPESTATUS[0]}"+"$exit_code"
echo "The maintainer of this repo is looking for a job..."
exit "$exit_code"
