#!/usr/bin/env Rscript
if(!exists("findwords", mode="function")) 
  source("findwords.R")
cnn <- findwords("cnna.txt") 
scnn <- freqwl(cnn) 
nwords <- length(scnn)
pdf("freqbarplot.pdf")
scnn90plus <- lengths(scnn[round(0.9 * nwords):nwords]) 
print(scnn90plus)
barplot(scnn90plus)
dev.off()
