#!/usr/bin/env bash
mkdir -p ~/storage/downloads/Rplots
find . -name "*.pdf" | parallel -I% --max-args 1 mv % ~/storage/downloads/Rplots
find . -name "*.png" | parallel -I% --max-args 1 mv % ~/storage/downloads/Rplots
