#!/usr/bin/env bash
libpath="${PREFIX}/lib/R/library/**/libs/*.so"
if [[ $OSTYPE == 'linux-gnu' ]]; then
  libpath="/usr/lib/R/library/**/libs/*.so"
fi
strip --strip-debug "$libpath"
du -csh "$libpath"
