#!/usr/bin/env bash
libpath="${PREFIX}/lib/R/library/**/libs/*.so"
if [[ $OSTYPE == 'linux-gnu' ]]; then
  libpath="/usr/lib/R/library/**/libs/*.so"
fi
stripcmd="strip --strip-debug ${libpath}"
eval "$stripcmd"
ducmd="du -csh ${libpath}"
eval "$ducmd"
